backend:
  name: github
  repo: devsandrine/EduTerra
  branch: main


media_folder: "images"
public_folder: "/images"



collections:


  - name: cours
    label: Fiches de révision
    folder: content/cours
    create: true
    slug: "{{slug}}"


    fields:


      - label: "Titre de la fiche"
        name: "title"
        widget: "string"



      - label: "Semestre"
        name: "semestre"
        widget: "select"
        options:

          - "S5"
          - "S6"



      - label: "Matière"
        name: "matiere"
        widget: "select"

        options:

          - "Psychologie de l'éducation"
          - "Sociologie de l'éducation"
          - "Didactique du français"
          - "Didactique des mathématiques"
          - "Anthropologie de l'éducation"
          - "Sociologie des professions"
          - "Psychanalyse et éducation"
          - "Évaluation en éducation"
          - "Technologies éducatives (TICE)"
          - "Mémoire"



      - label: "Type de fiche"
        name: "type"
        widget: "select"

        options:

          - "Cours"
          - "Auteur"
          - "Concept"
          - "Révision examen"



      - - label: "Auteur(s) important(s)"
  name: "auteurs"
  widget: "list"
  required: false
  field:
    label: "Auteur"
    name: "auteur"
    widget: "string"


      - label: "Concepts clés"
  name: "concepts"
  widget: "list"
  required: false
  field:
    label: "Concept"
    name: "concept"
    widget: "string"



      - label: "Objectifs du cours"
        name: "objectifs"
        widget: "markdown"
        required: false



      - label: "Résumé du cours"
        name: "body"
        widget: "markdown"



      - label: "À retenir pour l'examen"
        name: "a_retenir"
        widget: "markdown"
        required: false



      - label: "Questions possibles d'examen"
        name: "questions_examen"
        widget: "list"
        required: false



      - label: "Bibliographie"
        name: "bibliographie"
        widget: "markdown"
        required: false
