backend:
  name: github
  repo: devsandrine/EduTerra
  branch: main
  base_url: https://eduterra.pages.dev

media_folder: "images"
public_folder: "/images"

collections:
  - name: "cours"
    label: "Cours"
    folder: "content/cours"
    create: true
    slug: "{{slug}}"
    fields:

      - label: "Titre"
        name: "title"
        widget: "string"

      - label: "Semestre"
        name: "semestre"
        widget: "select"
        options:
          - "S5"
          - "S6"

      - label: "Matière"
        name: "matiere"
        widget: "select"
        options:
          - "Psychologie"
          - "Sociologie"
          - "Didactique"
          - "Anthropologie"
          - "Évaluation"
          - "TICE"

      - label: "Type de fiche"
        name: "type"
        widget: "select"
        options:
          - "Cours"
          - "Auteur"
          - "Concept"
          - "Révision examen"


      - label: "Auteur(s) important(s)"
        name: "auteurs"
        widget: "list"
        required: false
        field:
          label: "Auteur"
          name: "auteur"
          widget: "string"


      - label: "Concepts clés"
        name: "concepts"
        widget: "list"
        required: false
        field:
          label: "Concept"
          name: "concept"
          widget: "string"


      - label: "À retenir pour l'examen"
        name: "a_retenir"
        widget: "text"


      - label: "Questions possibles d'examen"
        name: "questions_examen"
        widget: "list"
        required: false
        field:
          label: "Question"
          name: "question"
          widget: "string"


      - label: "Résumé du cours"
        name: "resume"
        widget: "text"
